### ISSUE TITLE
`golangci-lint` job failure

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk#1255]
## Current Behavior

`golangci-lint` job fails on may repositories now.

To solve this, we need to check `ci` workflow of all NSM repositories and add:
```
  golangci-lint:
...
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
...
```

## Failure Information (for bugs)

Example: https://github.com/networkservicemesh/sdk-vpp/runs/5817274207?check_suite_focus=true

## Steps to Reproduce

1. Open PR in sdk
2. We can see that `golangci-lint` job is red
3. ...
