### ISSUE TITLE
Fix CI issues caused by moving to Go generics

### ISSUE THREAD

**Issue by wazsone** [networkservicemesh/sdk#1420]
Related to https://github.com/networkservicemesh/sdk/pull/1419

**Comment by denis-tingaikin** [comment]
@wazsone Before we close it, please lets minimalize scope of disabling revive linter. 

Please add text field for the added exclude-rules section.

```
   exclude-rules:
    - path: main.go
      linters:
        - revive
      text: "`%v`"
```
