### ISSUE TITLE
Decompose 'Topology aware scale-from-zero running of NSEs in response to NSC demand' and provide estimation time for each task

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#821]
## Description
The result of this issue should be a list of issues with approximate estimations related to _Topology aware scale-from-zero running of NSEs in response to NSC demand_.

## ROM

10d

**Comment by Bolodya1997** [comment]
@edwarnicke @fkautz 
Does it actually means that we want NSM to orchestrate NSE instances starts, stops and assigning to nodes? Do we want to start thinking of NSE as an entity provider instead of entity?
Please help me with some examples, because it is totally not quite clear to me.

**Comment by edwarnicke** [comment]
@Bolodya1997 Here was my thought roughly...  take the example of wanting a distributed bridge domain such that there's a Node local NSE for any requesting NSE.  So the service looks roughly like:

```yaml
---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: bridge-domain
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
             destinationSelector:
                nodeName: {{index .Src "nodeName"}}
    - match:
        route:
         - destination:
              destinationSelector:
                createProxyNSMgr: true
```

1. An NSC asks for an instance of of 'bridge-domain'.  Its request naturally includes its nodeName sourceLabel (added by NSMgr).
2. The NSMgr hits the first match, which tries to match us to an NSE with our nodeName.  There isn't one so it falls through to the next match.
3. The NSMgr then tries to find us an NSE with the label 'createProxyNSMgr' true as a destination label, and addresses the request to it.
4. The NSE for bridge-domain with 'createProxyNSMgr' true receives the request.  It interacts with the K8s API to launch an instance of an NSE for bridge-domain on 'nodeName'.  Once that has registered to the Registry, it returns an error
5. The NSMgr falls back to selection again, which means it attempts to match the first match, which now *does* match.
6. The NSMgr connects the NSC to its local bridge-domain NSE.
7. Time passes, perhaps new NSCs connect to the bridge-domain NSE on that node, perhaps they disconnect.
8. At some point, the bridge-domain NSE on that node has zero connections for a protracted period of time (say 10 minutes)
9. The bridge-domain NSE de-registers itself, waits a little longer, and then exits.

Which gets us to the form of the 'createProxyNSMgr' NSE.  My guess is we want this to be something that can be configured to perform this service for a variety of NSEs.  That's the fun part :)
