### ISSUE TITLE
NSE Composition: Discover should update Source/Destination labels

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#878]
## Overview

Discover chain element (or added new) should update `Request.Connection.Labels` to the next `Source` labels:
```go
func (s *discoverServer) Request(ctx context.Context, request *networkservice.NetworkServiceRequest) (*networkservice.Connection, error) {
	nsStream, _ := nsClient.Find(ctx, &registry.NetworkServiceQuery{
		NetworkService: &registry.NetworkService{
			Name:    request.Connection.NetworkService,
			Payload: request.Connection.Payload,
		},
	})
	ns, _ := nsStream.Recv()

	sourceLabels, destinationLabels := computeLabels(request.Connection.Labels, ns.Matches) // <-- compute labels

	nseStream, _ := nseClient.Find(ctx, &registry.NetworkServiceEndpointQuery{
		NetworkServiceEndpoint: &registry.NetworkServiceEndpoint{
			NetworkServiceNames: []string{ns.Name},
			NetworkServiceLabels: map[string]string{
				ns.Name: &registry.NetworkServiceLabels{
					Labels: sourceLabels, // <-- request NSE with computed source labels
				}
			}
		},
	})
	candidates := registry.ReadNetworkServiceEndpointList(nseStream)

	request.Connection.Labels = destinationLabels // <-- set new destination labels

	conn, _ := next.Server(ctx).Request(ctx, request)

	conn.Labels = sourceLabels // <-- set back source labels on return

	return conn
}
```

## References

* discover chain element - https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/discover/server.go

## Tests
1. Unit tests in `discover`.
2. Sandbox test with passthrough endpoint and composite NSE.

**Comment by denis-tingaikin** [comment]
We need also somehow store labels for conn.Id in metadata map.

@Bolodya1997 Will your proposal work correctly for cases when all nses locate on different nodes with their own nsmgr?

**Comment by Bolodya1997** [comment]
> We need also somehow store labels for conn.Id in metadata map.
> 
> @Bolodya1997 Will your proposal work correctly for cases when all nses locate on different nodes with their own nsmgr?

Yes, each NSMgr would store destination labels for its own clients.

**Comment by edwarnicke** [comment]
@Bolodya1997 NSMgr shouldn't generally be updating source destination labels except in some rare cases (like making sure we have Node, Cluster, etc labels correctly set).

The NSMgr should *not* be 'computing' source labels for the next hop... that's the NSEs responsiblity, not the NSMgrs.

**Comment by Bolodya1997** [comment]
@edwarnicke 
What do we actually mean by such request?
```
request: { NetworkService: ns, Labels: { label:a } }
```
### I need `ns` implemented with labels `{ label: a }`

If so, NSE just knows the labels it is implementing. It doesn't know what is the next hop in the NS route and so it cannot request right labels for the next hop.

#### Solution:
In such case NSMgr should find NSE by `{ label: a }` labels and switch labels in the request to the destination labels for the source matching `{ label: a }`.

### I need `ns` and my source labels are `{ label: a }`

If so, NSE still just knows the labels it is implementing. It doesn't know what was the previous hop in the NS route and so if NSE implementing labels for more than one NS route step, it cannot select right labels as a source for the next hop.

```
ns:
 - label:a -> label:b
 - step:0  -> step:1
 - label:b -> label:c
 - step:1  -> step:2
nse-1: { label:b, step:1 }
nse-2: { label:c }
nse-3: { step:2 }
```
If `nse-1` is requested with `label: a` it should use `label: b` as a source labels. If it is requested with `step: 0` it should use `step: 1`.

#### Solution:

In such case NSMgr should switch labels in request to the destination labels for the source matching `{ label: a }` and find NSE for these new labels.

### So

So it looks like for the both cases we still need NSMgr to rotate labels before requesting NSE.

**Comment by Bolodya1997** [comment]
Actually there is another solution for the (2) case I totally missed :)

So the usecase I have meant was something like this:
```yaml
---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: ns-example
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
          destinationSelector:
            zip: compress
        - destination:
          destinationSelector:
            tar: compress
    - match:
      sourceSelector:
        zip: compress
      route:
        - destination:
          destinationSelector:
            zip: passthrough-1
    - match:
      sourceSelector:
        tar: compress
      route:
        - destination:
          destinationSelector:
            tar: passthrough-1
...
    - match:
      sourceSelector:
        zip: passthrough-3
      route:
        - destination:
          destinationSelector:
            zip: decompress
    - match:
      sourceSelector:
        tar: passthrough-3
      route:
        - destination:
          destinationSelector:
            tar: decompress
    - match:
      sourceSelector:
        zip: decompress
      route:
        - destination:
          destinationSelector:
            zip: vpn
    - match:
      sourceSelector:
        tar: decompress
      route:
        - destination:
          destinationSelector:
            tar: vpn
```
![image](https://user-images.githubusercontent.com/20160689/117167288-52a1ef80-adf1-11eb-8cf3-83ed0705f7e8.png)

But instead of making such complex `ns-example` we can make `ns-zip` and `ns-tar` with `zip` and `tar` labels respective and so there will be no need to create multiple client labels for endpoint.
