### ISSUE TITLE
NSE Composition: Sandbox tests

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#880]
## Overview

1. Rework existing passthrough tests with composite NS. Add tests for complex tree scenarios.
2. Cover additional scenarios:
   1. Tree
      1. Add NS:
      ```yaml
      matches:
      - routes:
        - destination_selector:
            step: aa
      - source_selector:
          step: aa
        routes:
        - destination_selector:
            step: ab
      - source_selector:
          step: ab
        routes:
        - destination_selector:
            step: c
      - routes:
        - destination_selector:
            step: ba
      - source_selector:
          step: ba
        routes:
        - destination_selector:
            step: bb
      - source_selector:
          step: bb
        routes:
        - destination_selector:
            step: c
      - source_selector:
          step: c
        routes:
        - destination_selector:
            step: d
      ```
      2. Register `aa`, `ba`, `bb`, `c`, `d` Endpoints.
      3. Make and validate Request with a new Client : `aa` - 0, `ba` - 1, `bb` - 1, `c` - 1, `d` - 1.
      4. Register `ab` Endpoint.
      5. Make and validate Request with a new Client : `aa` - 1, `ab` - 1, `ba` - 1, `bb` - 1, `c` - 2, `d` - 2.
      6. Refresh and validate both Requests: `aa` - 2, `ab` - 2, `ba` - 2, `bb` - 2, `c` - 4, `d` - 4.
      7. Close both Requests.
   2. Multi label
      1. Add NS:
      ```yaml
      matches:
      - routes:
        - destination_selector:
            label_a: a
      - source_selector:
          label_a: a
          label_b: b
        routes:
        - destination_selector:
            label_a: aa
      - source_selector:
          label_a: aa
          label_b: bb
        routes:
        - destination_selector:
            label_a: aaa
            label_b: bbb
      ```
      2. Register Endpoints: `label_a: a, label_b: b`, `label_a: a, label_b: bb`, ..., `label_a: aaa, label_b: bbb` with 300 ms Request timeout for the client side
      3. Make and validate Request with a new Client: `label_a: a, label_b: b` -> `label_a: aa, label_b: bb` -> `label_a: aaa, label_b: bbb`

## References

* existing passthrough tests:
   * https://github.com/networkservicemesh/sdk/blob/5ab6206d4dcc62f09f79cc308aab1d5f6dc9202e/pkg/networkservice/chains/nsmgr/suite_test.go#L391
   * https://github.com/networkservicemesh/sdk/blob/5ab6206d4dcc62f09f79cc308aab1d5f6dc9202e/pkg/networkservice/chains/nsmgr/suite_test.go#L452

## Blockers

~Depends on #871, #878, #879.~
