### ISSUE TITLE
Discover behaviour in passthrough scenario

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/sdk#922]
## Intro
In the passthrough scenario, i stumbled upon a problem when composite NS contains 2 matches with empty source selector. 
In that case, when we start request, it'll go to endpoint1 with label from match1, but if it's endpoints sequence after has any unregistered(missing) endpoints, then it'll create infinite loop where endpoint1 calls itself.
It happens, because current discover don't know how to handle this case.

## Concrete example
NetworkServiceRegistry:
```
matches:
- source_selector:
    step: aa
  routes:
  - destination_selector:
      step: ab
- source_selector:
    step: ab
  routes:
  - destination_selector:
      step: c
- source_selector:
    step: ba
  routes:
  - destination_selector:
      step: bb
- source_selector:
    step: bb
  routes:
  - destination_selector:
      step: c
- source_selector:
    step: c
  routes:
  - destination_selector:
      step: d
- routes:
  - destination_selector:
      step: aa
- routes:
  - destination_selector:
      step: ba
```
tree diagram:
![example-tree](https://user-images.githubusercontent.com/26433765/118124881-66b4a500-b420-11eb-890c-cad7c9f78d48.jpg)

1. start single node, 
2. register network service described above
3. register endpoints for each label except 'ab'
4. create client and make request
5. discover will find 'aa' as first match with empty source selector
6. 'aa' will passthrough request further
7. 'aa' will not find endpoint 'ab' cause it doesn't exist
8. discover will try to find next endpoint and it find 'aa' again
9. infinite loop.. 

## Question
Do we expect cases with more than one matches with empty source selector?
If so, is it expected behaviour or we actually need to implement some logic, for breaking that cycle and trying next match with empty source?

**Comment by d-uzlov** [comment]
I tried to [replicate this in a sandbox test](https://github.com/d-uzlov/sdk/blob/983865519c7042b4add0144a41098c46f82932e8/pkg/networkservice/chains/nsmgr/alt_match_test.go) using gtest as an example and I got slightly different results:

Setup is as described, then we make an empty request:
1. Discover finds match with empty source selector, finds corresponding nse with `step: aa` label and goes there.
2. `aa` nse sets label `step: aa`.
3. Discover finds the match with `step: aa` source selector and then tries to find an nse with label `step: ab`. We didn't register such nse, so it doesn't find any matching nses, and then [hangs on waiting](https://github.com/networkservicemesh/sdk/blob/93d252947219d952fd428e98e86e63ea17550579/pkg/networkservice/common/discover/server.go#L148) for new nses until context expire, because we never create the `ab` nse.

I'm not sure if it's valid to have several matches with the same source selector (empty source selector in our case), so I tried to  use one match with an empty source selector and 2 routes (to `aa` and to `bb`), but this doesn't change _much_ for this test: discover server still only tries to find an nse with `step: ab` label, and never returns an error like `no matching endpoints found`.

**Comment by Bolodya1997** [comment]
Probably we can add here some system-level `entryPoint: true` label to be used instead of empty selector?
We can:
1. either set this label in the common client chain (not in the client chain from the ClientFactory) and unset it in the `discover` chain element
2. or check for this label if `Path.Index == 2` in `discover` and don't actually set it.

So then NS will be look like:
```yaml
matches:
- source_selector:
    entryPoint: true
  routes:
  - destination_selector:
      step: aa
- source_selector:
    entryPoint: true
  routes:
  - destination_selector:
      step: ba
...
```
And first step will be never selected again.

**Comment by edwarnicke** [comment]
@Bolodya1997 I think you may have some typo somewhere in your example... as it doesn't contain any empty matches.

I think basically what you are hitting on is a question of which behavior we take:

1. If a request matches a match, but there are no candidates for that match, go onto evaluate further matches.  This behavior is needed for Scale from Zero, but means we could hit a loop similar to what you are describing.
2. If a request matches a match, but there are no candidates for that match, go return an error.

You are basically suggesting that we have some means of hinting in the match as to which behavior we should take.

If I am reading correctly, you are suggesting marking some matches as 'entrypoints' meaning they should not be considered if we've previously matched another match for which we received no candidates.

I would suggest an alternative: 'fallthroughOnEmpty:true' (defaults to false).  If false, failure to find candidates results in an error.  If true, we can fall through to look for further matches that match.

So the rule effectively becomes:

1.  Walk through the matches in order.  
2. If you match a match, and it has candidates, those are the candidates.
3. If the match you matched does not result in candidates
     a. if fallthroughOnEmpty is false, return an error.
     b. if fallthroughOnEmpty is true, go onto evaluate the next match

Thoughts?

**Comment by edwarnicke** [comment]
@Bolodya1997 One other thing I'm confused about:

```yaml
matches:
- source_selector:
    entryPoint: true
  routes:
  - destination_selector:
      step: aa
- source_selector:
    entryPoint: true
  routes:
  - destination_selector:
      step: ba
...

```

Will never hit the match:
```yaml
- source_selector:
    entryPoint: true
  routes:
  - destination_selector:
      step: ba
...

```

Because it will always match on the first match.  If you wanted to load balance between aa and bb you'd want something like:

```yaml
matches:
- source_selector:
    entryPoint: true
  routes:
  - destination_selector:
      step: aa
  - destination_selector:
      step: ba
...

```

**Comment by Bolodya1997** [comment]
@edwarnicke
Yes, using single match for all empty source selectors solves the problem.

**Comment by edwarnicke** [comment]
> Yes, using single match for all empty source selectors solves the problem.

@Bolodya1997 Does it though?  If I use a single match for all empty sources, and we are behaving in the [If a request matches a match, but there are no candidates for that match, go onto evaluate further matches.](https://github.com/networkservicemesh/sdk/issues/922#issuecomment-841690859) mode... then a failure to find candidates could still have aa or bb running in a loop... it might just be a slightly larger loop( aa -> bb -> aa -> bb).  Or am I missing something?

**Comment by Bolodya1997** [comment]
@edwarnicke
You are right if we behave in such way. But for the tree case we don't need such behavior and so it starts working with single match and timeout for the passthrough request.

**Comment by Mixaster995** [comment]
I think i should write details about solution we found. It appeared that loop is a side effect of small fix for original problem(which is discover hangs, waiting for endpoint), so now we fixed the original problem and loops don't happen. 

let's star with same matches, as in the title, but with one empty match at the end
```
...
routes:
  - destination_selector:
      step: aa
  - destination_selector:
      step: ba
...
```
let's call 
```
- source_selector:
    step: aa
  routes:
  - destination_selector:
      step: ab
```
match_aa for brevity

again register all endpoints except `ab`
in current matching logic we'll match empty match for client and get 2 candidates: `aa, ba`. Next step we try to match match_aa and won't find valid endpoints for it, so we'll return empty list of candidates and then try again, until context timeout exceeded.
https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/discover/server.go#L173-L197

So (for the tree case) even though we have another correct route we'll never discover it. To break hanging we've added child context with timeout to endpoint connect client chain. With this change, when discover hangs, trying to find endpoint for match_aa, it'll cancel after a small timeout, go back to try next candidate `ba` and finally find the route.

@edwarnicke what do you think about this?
